name: Gradle Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Install dependencies
        run: |
          java -jar ./artifacts/app-card-delivery.jar &
          chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true